language: node_js

node_js:
  - "8"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

cache:
  directories:
    - "node_modules"