export const REQUEST_PERSON = "REQUEST_PERSON";
export const RECEIVE_PERSON = "RECEIVE_PERSON";
export const REQUEST_PEOPLE = "REQUEST_PEOPLE";
export const RECEIVE_PEOPLE = "RECEIVE_PEOPLE";
export const POPULATE_PEOPLE = "POPULATE_PEOPLE";
export const CHANGE_PAGE = "CHANGE_PAGE";